service: myservice
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9


functions:
  hello:
    handler: users.http.hello.handler
    events:
      - httpApi:
          path: /
          method: get

  shallow:
    handler: shallow.handler
    events:
      - httpApi:
          path: /shallow
          method: get


plugins:
  - serverless-offline

